// Story 16 quizzes
{
  quiz_id: 'quiz-16-1',
  story_id: '16',
  question_text: '日本の賃貸契約で、契約時に支払う必要があるものは何ですか？',
  question_type: '読解',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '敷金1ヶ月分、礼金1ヶ月分、仲介手数料1ヶ月分、それに最初の家賃',
  choices: [
    { choice_text: '敷金、礼金、仲介手数料、最初の家賃', is_correct: true, explanation: '正解です！日本の賃貸契約では、敷金（セキュリティデポジット）、礼金（お礼金）、仲介手数料（不動産屋への手数料）、そして最初の月の家賃を支払う必要があります。これを「初期費用」と呼び、家賃の4-5ヶ月分程度になることが多いです。' },
    { choice_text: '家賃だけ', is_correct: false, explanation: '不正解です。日本では家賃以外にも様々な初期費用が必要です。' },
    { choice_text: '更新料と家賃', is_correct: false, explanation: '不正解です。更新料は契約更新時（通常2年後）に支払うもので、初期費用ではありません。' },
    { choice_text: '保証人への支払い', is_correct: false, explanation: '不正解です。保証人への支払いは通常ありません。保証会社を利用する場合は、保証会社に料金を払います。' },
  ],
},
{
  quiz_id: 'quiz-16-2',
  story_id: '16',
  question_text: '「〜なければならない」はどんな意味ですか？',
  question_type: '語彙',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '〜なければならない = must / have to',
  choices: [
    { choice_text: 'must / have to', is_correct: true, explanation: '正解です！「〜なければならない」は義務を表す表現で、英語の "must" や "have to" に相当します。例：「書類を準備しなければならない」(I must prepare documents)。N3レベルの重要文法です。' },
    { choice_text: 'want to', is_correct: false, explanation: '不正解です。これは「〜たい」の意味です。' },
    { choice_text: 'can / be able to', is_correct: false, explanation: '不正解です。これは「〜できる」の意味です。' },
    { choice_text: 'may / might', is_correct: false, explanation: '不正解です。これは「〜かもしれない」の意味です。' },
  ],
},
{
  quiz_id: 'quiz-16-3',
  story_id: '16',
  question_text: '日本の賃貸契約で「礼金」とは何ですか？',
  question_type: '文化',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '礼金は大家さんへのお礼として支払うお金',
  choices: [
    { choice_text: '大家さんへのお礼として支払うお金（返金されない）', is_correct: true, explanation: '正解です！「礼金」は日本独特の習慣で、部屋を貸してくれる大家さんへのお礼として支払うお金です。退去時に返金されません。一方、「敷金」は担保として預けるお金で、退去時に部屋に問題がなければ返金されます。この違いを理解することが重要です。' },
    { choice_text: '退去時に返金されるお金', is_correct: false, explanation: '不正解です。それは「敷金」の説明です。礼金は返金されません。' },
    { choice_text: '毎月の家賃のこと', is_correct: false, explanation: '不正解です。礼金は初期費用の一部で、毎月支払うものではありません。' },
    { choice_text: '不動産屋への手数料', is_correct: false, explanation: '不正解です。不動産屋への手数料は「仲介手数料」と呼ばれます。' },
  ],
},
