// Story content for N1 Stories 23-25
// Final part - N1 Level advanced stories

const storyContentsN1Final = {
  // Story 23: N1 - 文学作品の解釈
  story23: {
    title: '文学作品の解釈',
    chapters: [
      {
        num: 1,
        content: `大学院の日本文学演習で、夏目漱石の「こころ」を精読することになった。この作品は、明治時代末期の知識人の内面を描いた傑作として知られている。

指導教授は「表層的な読解に留まらず、作品の深層構造を解明することが肝要だ」と強調した。単なる物語の理解ではなく、テクスト批評の手法を駆使して、作品に内在する多層的な意味を析出する必要がある。

まず、語り手の構造に注目した。作品は三部構成で、それぞれ異なる語り手の視点から描かれている。この複層的な語りの構造自体が、真実の相対性を暗示している。

特に興味深いのは、「先生」の遺書の部分だ。ここでは、罪の意識と自己欺瞞が錯綜し、読者は語り手の信頼性を疑わざるを得ない。

この不確実性こそが、作品の本質的な主題なのではないかという仮説を立てた。`,
        vocabulary: {
          "大学院": "graduate school",
          "日本文学演習": "Japanese literature seminar",
          "夏目漱石": "Natsume Soseki",
          "こころ": "Kokoro (title)",
          "精読": "close reading",
          "明治時代": "Meiji period",
          "末期": "end period",
          "知識人": "intellectual",
          "内面": "inner self",
          "描く": "to depict",
          "傑作": "masterpiece",
          "知られる": "to be known",
          "指導教授": "thesis advisor",
          "表層的": "superficial",
          "読解": "reading comprehension",
          "留まる": "to remain at",
          "深層構造": "deep structure",
          "解明": "elucidation",
          "解明する": "to elucidate",
          "肝要": "essential",
          "強調": "emphasis",
          "強調する": "to emphasize",
          "単なる": "mere",
          "物語": "story",
          "理解": "understanding",
          "テクスト批評": "textual criticism",
          "手法": "method",
          "駆使": "use",
          "駆使する": "to make full use of",
          "作品": "work",
          "内在": "inherent",
          "内在する": "to be inherent",
          "多層的": "multi-layered",
          "意味": "meaning",
          "析出": "extraction",
          "析出する": "to extract",
          "必要がある": "to need",
          "語り手": "narrator",
          "構造": "structure",
          "注目": "attention",
          "注目する": "to pay attention",
          "三部構成": "three-part structure",
          "それぞれ": "each",
          "異なる": "different",
          "視点": "perspective",
          "複層的": "multi-layered",
          "語り": "narration",
          "自体": "itself",
          "真実": "truth",
          "相対性": "relativity",
          "暗示": "suggestion",
          "暗示する": "to suggest",
          "特に": "especially",
          "興味深い": "interesting",
          "先生": "teacher (character)",
          "遺書": "suicide note",
          "部分": "part",
          "罪の意識": "sense of guilt",
          "自己欺瞞": "self-deception",
          "錯綜": "complication",
          "錯綜する": "to be complicated",
          "読者": "reader",
          "信頼性": "reliability",
          "疑う": "to doubt",
          "〜ざるを得ない": "cannot help but ~",
          "不確実性": "uncertainty",
          "こそ": "precisely, exactly",
          "本質的": "essential",
          "主題": "theme",
          "ではないか": "isn't it that ~",
          "仮説": "hypothesis",
          "立てる": "to establish"
        }
      },
      {
        num: 2,
        content: `次に、作品の歴史的・社会的文脈を検討した。明治という時代は、急速な西洋化と伝統的価値観の衝突が顕在化した時期だった。

「先生」という人物は、この時代的葛藤を体現している。彼の苦悩は、個人的な罪悪感に起因するだけでなく、時代そのものの矛盾を反映している。

友人を裏切って恋を成就させたという出来事は、表面的には個人の道徳的選択の問題だ。しかし、より深い次元では、近代的自我の覚醒とそれに伴う孤独という普遍的テーマを孕んでいる。

漱石が描こうとしたのは、近代化が個人にもたらす精神的危機ではなかったか。物質的豊かさと引き換えに失われる人間性の温もり、そして埋め難い心の空洞。

この解釈は、漱石の他の作品、特に後期三部作との関連において、一貫性を持つと考えられる。`,
        vocabulary: {
          "次に": "next",
          "歴史的": "historical",
          "社会的": "social",
          "文脈": "context",
          "検討": "examination",
          "検討する": "to examine",
          "明治": "Meiji (era)",
          "時代": "era",
          "急速": "rapid",
          "西洋化": "westernization",
          "伝統的": "traditional",
          "価値観": "values",
          "衝突": "conflict",
          "顕在化": "manifestation",
          "顕在化する": "to become manifest",
          "時期": "period",
          "人物": "character, person",
          "時代的": "of the era",
          "葛藤": "conflict",
          "体現": "embodiment",
          "体現する": "to embody",
          "彼": "he",
          "苦悩": "anguish",
          "個人的": "personal",
          "罪悪感": "sense of guilt",
          "起因": "origin",
          "起因する": "to originate from",
          "だけでなく": "not only",
          "そのもの": "itself",
          "矛盾": "contradiction",
          "反映": "reflection",
          "反映する": "to reflect",
          "友人": "friend",
          "裏切る": "to betray",
          "恋": "love",
          "成就": "fulfillment",
          "成就させる": "to fulfill",
          "出来事": "event",
          "表面的": "superficial",
          "道徳的": "moral",
          "選択": "choice",
          "問題": "problem",
          "より": "more",
          "深い": "deep",
          "次元": "dimension",
          "近代的": "modern",
          "自我": "ego, self",
          "覚醒": "awakening",
          "伴う": "to accompany",
          "孤独": "solitude",
          "普遍的": "universal",
          "テーマ": "theme",
          "孕む": "to contain, harbor",
          "漱石": "Soseki",
          "描く": "to depict",
          "しようとする": "to try to",
          "近代化": "modernization",
          "個人": "individual",
          "もたらす": "to bring",
          "精神的": "spiritual, mental",
          "危機": "crisis",
          "ではなかったか": "wasn't it that ~",
          "物質的": "material",
          "豊かさ": "richness",
          "引き換え": "exchange",
          "失われる": "to be lost",
          "人間性": "humanity",
          "温もり": "warmth",
          "埋め難い": "hard to fill",
          "心": "heart",
          "空洞": "void",
          "解釈": "interpretation",
          "他の": "other",
          "作品": "work",
          "特に": "especially",
          "後期三部作": "late trilogy",
          "関連": "relation",
          "において": "in",
          "一貫性": "consistency",
          "持つ": "to have",
          "考えられる": "to be considered"
        }
      },
      {
        num: 3,
        content: `演習では、他の院生との議論が白熱した。ある院生は「先生の自殺は、武士道精神の残滓である」という解釈を提示した。

確かに、明治天皇の崩御に際して乃木将軍が殉死したことが作中で言及されており、これが「先生」の決断に影響を与えたことは明白だ。

しかし、私はこれを単なる武士道精神の発露とは捉えない。むしろ、近代的個人としての自己決定権の行使と解釈すべきではないか。

別の院生は「Kの自殺こそが作品の核心だ」と主張した。確かに、Kの死は「先生」の人生を決定的に方向付けた。

だが、作品の構造を考えれば、Kの死は「先生」の語りを通してのみ読者に提示される。つまり、我々が知り得るKは、常に「先生」というフィルターを通した存在に過ぎない。`,
        vocabulary: {
          "演習": "seminar",
          "他の": "other",
          "院生": "graduate student",
          "議論": "discussion",
          "白熱": "heated",
          "白熱する": "to become heated",
          "ある": "certain",
          "自殺": "suicide",
          "武士道精神": "bushido spirit",
          "残滓": "remnant",
          "である": "to be",
          "解釈": "interpretation",
          "提示": "presentation",
          "提示する": "to present",
          "確かに": "certainly",
          "明治天皇": "Emperor Meiji",
          "崩御": "death (of emperor)",
          "際して": "on the occasion of",
          "乃木将軍": "General Nogi",
          "殉死": "following in death",
          "作中": "in the work",
          "言及": "mention",
          "言及される": "to be mentioned",
          "決断": "decision",
          "影響": "influence",
          "与える": "to give",
          "明白": "clear",
          "しかし": "however",
          "私": "I",
          "単なる": "mere",
          "発露": "manifestation",
          "捉える": "to regard",
          "むしろ": "rather",
          "近代的": "modern",
          "個人": "individual",
          "自己決定権": "right to self-determination",
          "行使": "exercise",
          "解釈すべき": "should interpret",
          "ではないか": "isn't it",
          "別の": "another",
          "K": "K (character)",
          "核心": "core",
          "主張": "assertion",
          "主張する": "to assert",
          "死": "death",
          "人生": "life",
          "決定的": "decisive",
          "方向付ける": "to direct",
          "だが": "but",
          "構造": "structure",
          "考える": "to consider",
          "〜ば": "if",
          "語り": "narration",
          "通して": "through",
          "のみ": "only",
          "読者": "reader",
          "提示される": "to be presented",
          "つまり": "in other words",
          "我々": "we",
          "知り得る": "can know",
          "常に": "always",
          "フィルター": "filter",
          "通した": "filtered through",
          "存在": "existence",
          "過ぎない": "nothing more than"
        }
      },
      {
        num: 4,
        content: `最終的に、私は以下のような論を展開することにした。「こころ」は、語りの不確実性を通じて、真実の認識可能性そのものを問う作品である。

我々は「先生」の告白を読むが、それが客観的真実である保証はない。記憶は常に主観的に再構成され、語りは必然的に選択的である。

作品が提起するのは、他者を真に理解することの不可能性だ。「私」は「先生」を理解しようと努めるが、最後まで完全な理解には至らない。

これは人間存在の根源的な孤独を示唆している。近代的個人は、自我を確立する代償として、他者との真の繋がりを失う。

この悲劇的認識こそが、「こころ」の持つ現代的意義ではないだろうか。我々が生きる現代社会においても、人間の本質的孤独は解消されていない。`,
        vocabulary: {
          "最終的": "final",
          "以下": "following",
          "論": "argument",
          "展開": "development",
          "展開する": "to develop",
          "こころ": "Kokoro (title)",
          "語り": "narration",
          "不確実性": "uncertainty",
          "通じて": "through",
          "真実": "truth",
          "認識可能性": "knowability",
          "そのもの": "itself",
          "問う": "to question",
          "作品": "work",
          "我々": "we",
          "先生": "teacher (character)",
          "告白": "confession",
          "読む": "to read",
          "それ": "it",
          "客観的": "objective",
          "保証": "guarantee",
          "記憶": "memory",
          "常に": "always",
          "主観的": "subjective",
          "再構成": "reconstruction",
          "再構成される": "to be reconstructed",
          "必然的": "inevitably",
          "選択的": "selective",
          "提起": "raising",
          "提起する": "to raise",
          "他者": "others",
          "真に": "truly",
          "理解": "understanding",
          "理解する": "to understand",
          "不可能性": "impossibility",
          "私": "I (character)",
          "努める": "to strive",
          "最後まで": "until the end",
          "完全": "complete",
          "至る": "to reach",
          "人間存在": "human existence",
          "根源的": "fundamental",
          "孤独": "solitude",
          "示唆": "suggestion",
          "示唆する": "to suggest",
          "近代的": "modern",
          "個人": "individual",
          "自我": "ego, self",
          "確立": "establishment",
          "確立する": "to establish",
          "代償": "price, cost",
          "繋がり": "connection",
          "失う": "to lose",
          "悲劇的": "tragic",
          "認識": "recognition",
          "こそ": "precisely",
          "持つ": "to have",
          "現代的": "contemporary",
          "意義": "significance",
          "ではないだろうか": "isn't it that ~",
          "生きる": "to live",
          "現代社会": "modern society",
          "において": "in",
          "も": "also",
          "本質的": "essential",
          "解消": "resolution",
          "解消される": "to be resolved"
        }
      },
      {
        num: 5,
        content: `演習での発表は、予想以上の反響を呼んだ。教授からは「斬新な視点だ。ただし、テクストの根拠をもっと綿密に示す必要がある」との講評を受けた。

その後、数週間かけて論文を精緻化した。本文からの引用を増やし、各論点に対する典拠を明確にした。

特に注力したのは、作品の言語的特徴の分析だ。「先生」の語りには、頻繁に曖昧な表現や婉曲的な言い回しが用いられている。

これは単なる文体の問題ではなく、語り手の心理的防衛機制の表れだと解釈できる。真実を語りながら、同時にそれから目を背けようとする矛盾した心性が、言語レベルで現れているのだ。

最終的に完成した論文は、学内誌に掲載されることになった。文学研究の奥深さと、一つの作品から引き出せる多様な解釈の可能性を実感した貴重な経験だった。`,
        vocabulary: {
          "演習": "seminar",
          "発表": "presentation",
          "予想以上": "more than expected",
          "反響": "response",
          "呼ぶ": "to call, evoke",
          "教授": "professor",
          "斬新": "novel, fresh",
          "視点": "viewpoint",
          "ただし": "however",
          "テクスト": "text",
          "根拠": "basis",
          "もっと": "more",
          "綿密に": "thoroughly",
          "示す": "to show",
          "必要がある": "to need",
          "講評": "critique",
          "受ける": "to receive",
          "その後": "after that",
          "数週間": "several weeks",
          "かけて": "taking (time)",
          "論文": "paper",
          "精緻化": "refinement",
          "精緻化する": "to refine",
          "本文": "text, body",
          "引用": "quotation",
          "増やす": "to increase",
          "各": "each",
          "論点": "point of argument",
          "対する": "toward",
          "典拠": "source",
          "明確": "clear",
          "明確にする": "to clarify",
          "特に": "especially",
          "注力": "concentration",
          "注力する": "to concentrate on",
          "言語的": "linguistic",
          "特徴": "characteristic",
          "分析": "analysis",
          "語り": "narration",
          "頻繁に": "frequently",
          "曖昧": "ambiguous",
          "表現": "expression",
          "婉曲的": "euphemistic",
          "言い回し": "wording",
          "用いられる": "to be used",
          "単なる": "mere",
          "文体": "style",
          "問題": "problem",
          "語り手": "narrator",
          "心理的": "psychological",
          "防衛機制": "defense mechanism",
          "表れ": "manifestation",
          "解釈": "interpretation",
          "解釈できる": "can be interpreted",
          "真実": "truth",
          "語る": "to tell",
          "同時に": "at the same time",
          "目を背ける": "to turn away from",
          "しようとする": "to try to",
          "矛盾": "contradiction",
          "矛盾した": "contradictory",
          "心性": "mentality",
          "言語レベル": "linguistic level",
          "現れる": "to appear",
          "最終的": "finally",
          "完成": "completion",
          "完成する": "to complete",
          "学内誌": "university journal",
          "掲載": "publication",
          "掲載される": "to be published",
          "文学研究": "literary research",
          "奥深さ": "profundity",
          "一つ": "one",
          "引き出せる": "can be drawn out",
          "多様": "diverse",
          "可能性": "possibility",
          "実感": "real feeling",
          "実感する": "to realize",
          "貴重": "precious",
          "経験": "experience"
        }
      }
    ],
    quizzes: [
      {
        id: 'quiz-23-1',
        question: '「こころ」の作者は誰ですか。',
        type: '読解',
        choices: [
          { text: '夏目漱石', correct: true, explanation: '最初に「夏目漱石の「こころ」を精読する」と書かれています。' },
          { text: '芥川龍之介', correct: false, explanation: '芥川龍之介は作者ではありません。' },
          { text: '太宰治', correct: false, explanation: '太宰治は作者ではありません。' },
          { text: '川端康成', correct: false, explanation: '川端康成は作者ではありません。' }
        ]
      },
      {
        id: 'quiz-23-2',
        question: '主人公が立てた仮説は何ですか。',
        type: '読解',
        choices: [
          { text: '語りの不確実性が作品の本質的な主題である', correct: true, explanation: '「この不確実性こそが、作品の本質的な主題なのではないか」という仮説を立てたと書かれています。' },
          { text: '武士道精神が主題である', correct: false, explanation: 'それは別の院生の解釈です。' },
          { text: 'Kの死が核心である', correct: false, explanation: 'それも別の院生の主張です。' },
          { text: '恋愛が主題である', correct: false, explanation: 'それは主人公の仮説ではありません。' }
        ]
      },
      {
        id: 'quiz-23-3',
        question: '「体現する」の意味は何ですか。',
        type: '語彙',
        choices: [
          { text: '抽象的なものを具体的な形で示す', correct: true, explanation: '「体現する」は抽象的な概念を具体的に表すことです。' },
          { text: '隠す', correct: false, explanation: 'それは逆の意味です。' },
          { text: '破壊する', correct: false, explanation: 'それは「破壊する」です。' },
          { text: '無視する', correct: false, explanation: 'それは「無視する」です。' }
        ]
      },
      {
        id: 'quiz-23-4',
        question: '主人公が特に注力した分析は何ですか。',
        type: '読解',
        choices: [
          { text: '作品の言語的特徴の分析', correct: true, explanation: '「特に注力したのは、作品の言語的特徴の分析だ」と書かれています。' },
          { text: '登場人物の性格分析', correct: false, explanation: 'それが特に注力した点とは書かれていません。' },
          { text: '時代背景の調査', correct: false, explanation: 'それは検討しましたが、特に注力したとは書かれていません。' },
          { text: '作者の伝記研究', correct: false, explanation: 'それは言及されていません。' }
        ]
      },
      {
        id: 'quiz-23-5',
        question: '「綿密に」の意味は何ですか。',
        type: '語彙',
        choices: [
          { text: '細かく注意深く', correct: true, explanation: '「綿密に」は詳しく細かく、注意深い様子を表します。' },
          { text: '大雑把に', correct: false, explanation: 'それは逆の意味です。' },
          { text: '素早く', correct: false, explanation: 'それは「素早く」です。' },
          { text: '適当に', correct: false, explanation: 'それは逆の意味です。' }
        ]
      }
    ]
  },

  // Story 24: N1 - 国際関係の考察
  story24: {
    title: '国際関係の考察',
    chapters: [
      {
        num: 1,
        content: `国際関係論のゼミで、「東アジアにおける多国間安全保障の可能性」というテーマで研究発表を行うことになった。これは極めて複雑かつ論争的な問題だ。

現在の東アジアは、歴史認識問題、領土紛争、経済的相互依存、イデオロギー対立など、多様な要因が錯綜している。この地域で多国間安全保障枠組みを構築することは、理論的には望ましいが、実際には多くの障壁がある。

まず、欧州における集団安全保障体制の発展過程を参照した。NATOやOSCEの経験は、共通の脅威認識と価値観の共有が不可欠であることを示している。

しかし、東アジアにはそのような基盤が欠如している。むしろ、各国の国益が鋭く対立し、不信感が根深い。

それでも、地域の平和と安定は全ての国に利益をもたらす。この共通利益を基礎として、段階的なアプローチを模索する余地はあるのではないか。`,
        vocabulary: {
          "国際関係論": "international relations",
          "ゼミ": "seminar",
          "東アジア": "East Asia",
          "多国間": "multilateral",
          "安全保障": "security",
          "可能性": "possibility",
          "テーマ": "theme",
          "研究発表": "research presentation",
          "行う": "to conduct",
          "極めて": "extremely",
          "複雑": "complex",
          "かつ": "and",
          "論争的": "controversial",
          "問題": "issue",
          "現在": "current",
          "歴史認識問題": "historical perception issue",
          "領土紛争": "territorial dispute",
          "経済的": "economic",
          "相互依存": "interdependence",
          "イデオロギー": "ideology",
          "対立": "conflict",
          "多様": "diverse",
          "要因": "factor",
          "錯綜": "complication",
          "錯綜する": "to be complicated",
          "地域": "region",
          "枠組み": "framework",
          "構築": "construction",
          "構築する": "to construct",
          "理論的": "theoretical",
          "望ましい": "desirable",
          "実際": "actually",
          "多く": "many",
          "障壁": "barrier",
          "欧州": "Europe",
          "集団安全保障体制": "collective security system",
          "発展過程": "development process",
          "参照": "reference",
          "参照する": "to refer to",
          "NATO": "North Atlantic Treaty Organization",
          "OSCE": "Organization for Security and Cooperation in Europe",
          "経験": "experience",
          "共通": "common",
          "脅威": "threat",
          "認識": "perception",
          "価値観": "values",
          "共有": "sharing",
          "不可欠": "indispensable",
          "示す": "to show",
          "しかし": "however",
          "基盤": "foundation",
          "欠如": "lack",
          "欠如する": "to lack",
          "むしろ": "rather",
          "各国": "each country",
          "国益": "national interest",
          "鋭く": "sharply",
          "不信感": "distrust",
          "根深い": "deep-rooted",
          "それでも": "nevertheless",
          "平和": "peace",
          "安定": "stability",
          "全て": "all",
          "利益": "benefit",
          "もたらす": "to bring",
          "共通利益": "common interest",
          "基礎": "basis",
          "段階的": "gradual",
          "アプローチ": "approach",
          "模索": "search",
          "模索する": "to search for",
          "余地": "room",
          "ではないか": "isn't there"
        }
      },
      {
        num: 2,
        content: `信頼醸成措置（CBM）から始めるべきだという結論に至った。軍事的透明性の向上、高官レベルでの定期的対話、危機管理メカニズムの整備など、小さな一歩を積み重ねることが重要だ。

ARF（ASEAN地域フォーラム）の実践は示唆に富む。この枠組みは、拘束力のある同盟ではなく、対話と協調を重視する緩やかな協議体だ。

しかし、ARFの限界も明白だ。具体的な紛争解決能力に欠け、実効性が疑問視されている。より強力な制度的枠組みが必要だという議論も説得力がある。

一方で、性急な制度化は逆効果になりかねない。各国の主権に対する懸念が強く、超国家的な権限を持つ機構への抵抗は大きい。

したがって、機能主義的アプローチが現実的だ。特定の機能分野での協力を深化させ、その成功体験を基に徐々に協力範囲を拡大していく戦略だ。`,
        vocabulary: {
          "信頼醸成措置": "confidence-building measures",
          "CBM": "confidence-building measures",
          "始める": "to begin",
          "べき": "should",
          "結論": "conclusion",
          "至る": "to reach",
          "軍事的": "military",
          "透明性": "transparency",
          "向上": "improvement",
          "高官": "high official",
          "レベル": "level",
          "定期的": "regular",
          "対話": "dialogue",
          "危機管理": "crisis management",
          "メカニズム": "mechanism",
          "整備": "establishment",
          "小さな": "small",
          "一歩": "step",
          "積み重ねる": "to pile up",
          "重要": "important",
          "ARF": "ASEAN Regional Forum",
          "ASEAN地域フォーラム": "ASEAN Regional Forum",
          "実践": "practice",
          "示唆に富む": "suggestive, instructive",
          "枠組み": "framework",
          "拘束力": "binding power",
          "同盟": "alliance",
          "協調": "cooperation",
          "重視": "emphasis",
          "重視する": "to emphasize",
          "緩やか": "loose, flexible",
          "協議体": "consultative body",
          "限界": "limit",
          "明白": "clear",
          "具体的": "concrete",
          "紛争解決": "dispute resolution",
          "能力": "ability",
          "欠ける": "to lack",
          "実効性": "effectiveness",
          "疑問視": "questioning",
          "疑問視される": "to be questioned",
          "より": "more",
          "強力": "powerful",
          "制度的": "institutional",
          "必要": "necessary",
          "議論": "argument",
          "説得力": "persuasiveness",
          "説得力がある": "to be persuasive",
          "一方で": "on the other hand",
          "性急": "hasty",
          "制度化": "institutionalization",
          "逆効果": "counterproductive",
          "なりかねない": "might become",
          "各国": "each country",
          "主権": "sovereignty",
          "対する": "toward",
          "懸念": "concern",
          "強い": "strong",
          "超国家的": "supranational",
          "権限": "authority",
          "持つ": "to have",
          "機構": "organization",
          "抵抗": "resistance",
          "大きい": "large",
          "したがって": "therefore",
          "機能主義的": "functionalist",
          "アプローチ": "approach",
          "現実的": "realistic",
          "特定": "specific",
          "機能分野": "functional area",
          "協力": "cooperation",
          "深化": "deepening",
          "深化させる": "to deepen",
          "成功体験": "success experience",
          "基": "basis",
          "徐々に": "gradually",
          "範囲": "scope",
          "拡大": "expansion",
          "拡大する": "to expand",
          "戦略": "strategy"
        }
      },
      {
        num: 3,
        content: `具体的な提言として、海洋安全保障分野での協力を挙げた。海賊対策、海難救助、海洋環境保護など、非伝統的安全保障課題は政治的に敏感でなく、協力の敷居が低い。

実際、ソマリア沖での海賊対策では、中国、日本、韓国の海軍が事実上協力している。このような実績を基に、制度化された協力枠組みを構築できるのではないか。

次に、経済的相互依存の深化が安全保障協力を促進するという議論を検討した。商業的平和論は、貿易と投資の拡大が国家間の紛争を抑制すると主張する。

しかし、この理論には批判もある。第一次世界大戦前の欧州も高度な経済的相互依存関係にあったが、戦争を防げなかった。経済的紐帯は必要条件だが、十分条件ではない。

それでも、経済協力が対話の契機を提供し、相互理解を深める効果は否定できない。`,
        vocabulary: {
          "具体的": "concrete",
          "提言": "proposal",
          "海洋安全保障": "maritime security",
          "分野": "field",
          "協力": "cooperation",
          "挙げる": "to cite",
          "海賊対策": "anti-piracy measures",
          "海難救助": "maritime rescue",
          "海洋環境保護": "marine environmental protection",
          "非伝統的": "non-traditional",
          "安全保障課題": "security issue",
          "政治的": "political",
          "敏感": "sensitive",
          "敷居": "threshold",
          "低い": "low",
          "実際": "actually",
          "ソマリア沖": "off Somalia",
          "中国": "China",
          "日本": "Japan",
          "韓国": "South Korea",
          "海軍": "navy",
          "事実上": "de facto",
          "実績": "track record",
          "基": "basis",
          "制度化": "institutionalization",
          "制度化された": "institutionalized",
          "枠組み": "framework",
          "構築": "construction",
          "構築できる": "can be constructed",
          "ではないか": "couldn't we",
          "次に": "next",
          "経済的": "economic",
          "相互依存": "interdependence",
          "深化": "deepening",
          "促進": "promotion",
          "促進する": "to promote",
          "議論": "argument",
          "検討": "examination",
          "検討する": "to examine",
          "商業的平和論": "commercial peace theory",
          "貿易": "trade",
          "投資": "investment",
          "拡大": "expansion",
          "国家間": "interstate",
          "紛争": "conflict",
          "抑制": "suppression",
          "抑制する": "to suppress",
          "主張": "assertion",
          "主張する": "to assert",
          "しかし": "however",
          "理論": "theory",
          "批判": "criticism",
          "第一次世界大戦": "World War I",
          "前": "before",
          "欧州": "Europe",
          "も": "also",
          "高度": "high degree",
          "関係": "relationship",
          "戦争": "war",
          "防ぐ": "to prevent",
          "防げる": "can prevent",
          "紐帯": "tie, bond",
          "必要条件": "necessary condition",
          "十分条件": "sufficient condition",
          "それでも": "nevertheless",
          "契機": "opportunity",
          "提供": "provision",
          "提供する": "to provide",
          "相互理解": "mutual understanding",
          "深める": "to deepen",
          "効果": "effect",
          "否定": "denial",
          "否定できる": "can be denied"
        }
      },
      {
        num: 4,
        content: `ゼミでの発表では、激しい質疑応答があった。特に鋭い指摘は、「理想主義的すぎる」というものだった。

確かに、現実の国際政治はパワーポリティクスに支配されている。各国は自国の安全を最優先し、多国間協力は二の次だ。

しかし、だからこそ制度的枠組みが必要なのだ。アナーキーな国際システムにおいて、制度は予測可能性を高め、取引コストを削減する。

別の批判は、「中国の台頭をどう扱うか」という点だった。これは核心的な問題だ。

中国を包摂するのか、あるいは抑止するのか。この二元論は不毛だと私は考える。包摂と抑止を組み合わせた、ヘッジング戦略が現実的ではないか。`,
        vocabulary: {
          "ゼミ": "seminar",
          "発表": "presentation",
          "激しい": "intense",
          "質疑応答": "Q&A session",
          "特に": "especially",
          "鋭い": "sharp",
          "指摘": "point",
          "理想主義的": "idealistic",
          "すぎる": "too much",
          "確かに": "certainly",
          "現実": "reality",
          "国際政治": "international politics",
          "パワーポリティクス": "power politics",
          "支配": "domination",
          "支配される": "to be dominated",
          "各国": "each country",
          "自国": "own country",
          "安全": "security",
          "最優先": "top priority",
          "最優先する": "to prioritize",
          "多国間協力": "multilateral cooperation",
          "二の次": "secondary",
          "だからこそ": "that's exactly why",
          "制度的": "institutional",
          "枠組み": "framework",
          "必要": "necessary",
          "アナーキー": "anarchic",
          "国際システム": "international system",
          "において": "in",
          "制度": "institution",
          "予測可能性": "predictability",
          "高める": "to increase",
          "取引コスト": "transaction cost",
          "削減": "reduction",
          "削減する": "to reduce",
          "別の": "another",
          "批判": "criticism",
          "中国": "China",
          "台頭": "rise",
          "どう": "how",
          "扱う": "to handle",
          "点": "point",
          "核心的": "central",
          "問題": "issue",
          "包摂": "inclusion",
          "包摂する": "to include",
          "あるいは": "or",
          "抑止": "deterrence",
          "抑止する": "to deter",
          "二元論": "dualism",
          "不毛": "sterile, fruitless",
          "考える": "to think",
          "組み合わせる": "to combine",
          "ヘッジング": "hedging",
          "戦略": "strategy",
          "現実的": "realistic",
          "ではないか": "isn't it"
        }
      },
      {
        num: 5,
        content: `最終的に、論文では以下のような結論を提示した。東アジアにおける多国間安全保障の実現は困難だが、不可能ではない。

短期的には、信頼醸成と機能的協力の深化を図る。中期的には、制度的枠組みを段階的に構築する。長期的には、共通の安全保障アイデンティティの形成を目指す。

この段階的アプローチは、欧州の経験に学びつつ、東アジアの特殊性を考慮したものだ。

教授からは「現実を直視しながらも、建設的な提言を行っている」との評価を得た。同時に「理論的精緻化が必要」との課題も指摘された。

この研究を通じて、国際関係における理想と現実のバランスを取ることの難しさを痛感した。しかし、学問の役割は、現状を追認することではなく、より良い未来を構想することにあるのではないだろうか。`,
        vocabulary: {
          "最終的": "finally",
          "論文": "paper",
          "以下": "following",
          "結論": "conclusion",
          "提示": "presentation",
          "提示する": "to present",
          "東アジア": "East Asia",
          "多国間安全保障": "multilateral security",
          "実現": "realization",
          "困難": "difficult",
          "不可能": "impossible",
          "短期的": "short-term",
          "信頼醸成": "confidence building",
          "機能的": "functional",
          "協力": "cooperation",
          "深化": "deepening",
          "図る": "to aim for",
          "中期的": "medium-term",
          "制度的": "institutional",
          "枠組み": "framework",
          "段階的": "gradual",
          "構築": "construction",
          "構築する": "to construct",
          "長期的": "long-term",
          "共通": "common",
          "アイデンティティ": "identity",
          "形成": "formation",
          "目指す": "to aim for",
          "段階的アプローチ": "gradual approach",
          "欧州": "Europe",
          "経験": "experience",
          "学ぶ": "to learn",
          "つつ": "while",
          "特殊性": "particularity",
          "考慮": "consideration",
          "考慮する": "to consider",
          "教授": "professor",
          "現実": "reality",
          "直視": "facing",
          "直視する": "to face",
          "ながらも": "while",
          "建設的": "constructive",
          "提言": "proposal",
          "行う": "to make",
          "評価": "evaluation",
          "得る": "to obtain",
          "同時に": "at the same time",
          "理論的": "theoretical",
          "精緻化": "refinement",
          "必要": "necessary",
          "課題": "task",
          "指摘": "pointing out",
          "指摘される": "to be pointed out",
          "研究": "research",
          "通じて": "through",
          "国際関係": "international relations",
          "における": "in",
          "理想": "ideal",
          "バランス": "balance",
          "取る": "to achieve",
          "難しさ": "difficulty",
          "痛感": "keen realization",
          "痛感する": "to keenly realize",
          "しかし": "however",
          "学問": "scholarship",
          "役割": "role",
          "現状": "current situation",
          "追認": "approval",
          "追認する": "to approve",
          "より良い": "better",
          "未来": "future",
          "構想": "conception",
          "構想する": "to conceive",
          "にある": "to lie in",
          "ではないだろうか": "isn't it that"
        }
      }
    ],
    quizzes: [
      {
        id: 'quiz-24-1',
        question: '主人公の研究テーマは何ですか。',
        type: '読解',
        choices: [
          { text: '東アジアにおける多国間安全保障の可能性', correct: true, explanation: '最初に「東アジアにおける多国間安全保障の可能性」というテーマで研究発表を行うと書かれています。' },
          { text: '欧州の集団安全保障', correct: false, explanation: 'それは参照した事例です。' },
          { text: '中国の外交政策', correct: false, explanation: 'それは研究の一部です。' },
          { text: '経済的相互依存', correct: false, explanation: 'それは検討した要素の一つです。' }
        ]
      },
      {
        id: 'quiz-24-2',
        question: '主人公が最初に提案したアプローチは何ですか。',
        type: '読解',
        choices: [
          { text: '信頼醸成措置（CBM）から始める', correct: true, explanation: '「信頼醸成措置（CBM）から始めるべきだという結論に至った」と書かれています。' },
          { text: '軍事同盟の締結', correct: false, explanation: 'それは提案されていません。' },
          { text: '経済制裁', correct: false, explanation: 'それは提案されていません。' },
          { text: '領土問題の即時解決', correct: false, explanation: 'それは提案されていません。' }
        ]
      },
      {
        id: 'quiz-24-3',
        question: '「根深い」の意味は何ですか。',
        type: '語彙',
        choices: [
          { text: '深く根付いている、容易には変わらない', correct: true, explanation: '「根深い」は問題や感情が深く定着していることを表します。' },
          { text: '浅い', correct: false, explanation: 'それは逆の意味です。' },
          { text: '新しい', correct: false, explanation: 'それは「新しい」です。' },
          { text: '一時的', correct: false, explanation: 'それは逆の意味です。' }
        ]
      },
      {
        id: 'quiz-24-4',
        question: '商業的平和論への批判として挙げられた例は何ですか。',
        type: '読解',
        choices: [
          { text: '第一次世界大戦前の欧州も経済的相互依存があったが戦争を防げなかった', correct: true, explanation: '「第一次世界大戦前の欧州も高度な経済的相互依存関係にあったが、戦争を防げなかった」と書かれています。' },
          { text: '冷戦時代の米ソ関係', correct: false, explanation: 'それは例として挙げられていません。' },
          { text: '現代の米中関係', correct: false, explanation: 'それは例として挙げられていません。' },
          { text: '日韓関係', correct: false, explanation: 'それは例として挙げられていません。' }
        ]
      },
      {
        id: 'quiz-24-5',
        question: '「痛感する」の意味は何ですか。',
        type: '語彙',
        choices: [
          { text: '深く感じる、強く実感する', correct: true, explanation: '「痛感する」は何かを強く、深く感じることです。' },
          { text: '軽く感じる', correct: false, explanation: 'それは逆の意味です。' },
          { text: '無視する', correct: false, explanation: 'それは逆の意味です。' },
          { text: '忘れる', correct: false, explanation: 'それは逆の意味です。' }
        ]
      }
    ]
  },

  // Story 25: N1 - 伝統文化の継承
  story25: {
    title: '伝統文化の継承',
    chapters: [
      {
        num: 1,
        content: `文化人類学の視点から、日本の伝統工芸の継承問題を研究することにした。グローバル化と少子高齢化が進む中で、多くの伝統技術が存亡の危機に瀕している。

京都の西陣織を事例として選んだ。この織物は、1200年以上の歴史を持ち、高度な技術と美意識の結晶だ。しかし、後継者不足と需要の減少により、職人の数は最盛期の10分の1以下に減少している。

まず、現地調査を実施した。90歳になる織元の親方に話を聞くことができた。彼の語る伝統技術の奥深さは圧巻だった。

「この技は、見て盗むもんや。言葉で教えられるもんやない」という言葉が印象的だった。暗黙知の伝達という、伝統工芸継承の本質的困難が端的に表現されている。

しかし、それだけが問題ではない。経済的持続可能性の欠如が、より根本的な課題だ。`,
        vocabulary: {
          "文化人類学": "cultural anthropology",
          "視点": "perspective",
          "伝統工芸": "traditional crafts",
          "継承": "succession, inheritance",
          "問題": "problem",
          "研究": "research",
          "研究する": "to research",
          "グローバル化": "globalization",
          "少子高齢化": "declining birthrate and aging population",
          "進む": "to advance",
          "中": "while",
          "多く": "many",
          "伝統技術": "traditional technique",
          "存亡": "survival",
          "危機": "crisis",
          "瀕する": "to face",
          "京都": "Kyoto",
          "西陣織": "Nishijin weaving",
          "事例": "case",
          "選ぶ": "to choose",
          "織物": "textile",
          "歴史": "history",
          "持つ": "to have",
          "高度": "advanced",
          "技術": "technique",
          "美意識": "aesthetic sense",
          "結晶": "crystallization",
          "しかし": "however",
          "後継者不足": "lack of successors",
          "需要": "demand",
          "減少": "decrease",
          "職人": "craftsperson",
          "数": "number",
          "最盛期": "peak period",
          "10分の1": "one-tenth",
          "以下": "below",
          "減少する": "to decrease",
          "現地調査": "field research",
          "実施": "implementation",
          "実施する": "to implement",
          "90歳": "90 years old",
          "織元": "weaving house",
          "親方": "master",
          "話": "story",
          "聞く": "to listen",
          "語る": "to tell",
          "奥深さ": "profundity",
          "圧巻": "overwhelming",
          "技": "skill",
          "見て盗む": "to learn by watching",
          "もん": "thing (dialectal)",
          "や": "is (dialectal)",
          "言葉": "words",
          "教える": "to teach",
          "印象的": "impressive",
          "暗黙知": "tacit knowledge",
          "伝達": "transmission",
          "本質的": "essential",
          "困難": "difficulty",
          "端的に": "briefly, concisely",
          "表現": "expression",
          "表現される": "to be expressed",
          "だけ": "only",
          "経済的": "economic",
          "持続可能性": "sustainability",
          "欠如": "lack",
          "より": "more",
          "根本的": "fundamental",
          "課題": "issue"
        }
      },
      {
        num: 2,
        content: `若手職人へのインタビューも行った。30代の職人は、厳しい現実を率直に語った。

「親方の下で10年修行して、やっと一人前になれる。けど、その間の収入は月15万円程度。結婚も子育ても難しい」

技術の習得には長い年月を要するが、その間の経済的保障がない。これでは、優秀な若者が伝統工芸の道を選ぶはずがない。

さらに、市場の変化も深刻だ。着物を着る機会が激減し、西陣織の需要は年々縮小している。高級品としての位置づけも、バブル崩壊後は通用しなくなった。

一部の職人は、新しい市場開拓に挑戦している。インテリアファブリックや小物への応用、海外市場への展開など、伝統技術の現代的活用を模索している。`,
        vocabulary: {
          "若手": "young",
          "職人": "craftsperson",
          "インタビュー": "interview",
          "行う": "to conduct",
          "30代": "in one's thirties",
          "厳しい": "strict, severe",
          "現実": "reality",
          "率直に": "frankly",
          "語る": "to tell",
          "親方": "master",
          "下": "under",
          "修行": "training",
          "修行する": "to train",
          "やっと": "finally",
          "一人前": "fully qualified",
          "なれる": "can become",
          "けど": "but (casual)",
          "その間": "during that time",
          "収入": "income",
          "月": "month",
          "程度": "about",
          "結婚": "marriage",
          "子育て": "child rearing",
          "難しい": "difficult",
          "技術": "technique",
          "習得": "acquisition",
          "長い": "long",
          "年月": "years",
          "要する": "to require",
          "間": "during",
          "経済的": "economic",
          "保障": "guarantee",
          "優秀": "excellent",
          "若者": "young people",
          "伝統工芸": "traditional crafts",
          "道": "path",
          "選ぶ": "to choose",
          "はずがない": "cannot be expected to",
          "さらに": "furthermore",
          "市場": "market",
          "変化": "change",
          "深刻": "serious",
          "着物": "kimono",
          "着る": "to wear",
          "機会": "opportunity",
          "激減": "sharp decrease",
          "激減する": "to decrease sharply",
          "需要": "demand",
          "年々": "year by year",
          "縮小": "contraction",
          "縮小する": "to contract",
          "高級品": "luxury goods",
          "位置づけ": "positioning",
          "バブル崩壊": "bubble burst",
          "後": "after",
          "通用": "acceptance",
          "通用する": "to be accepted",
          "一部": "some",
          "新しい": "new",
          "市場開拓": "market development",
          "挑戦": "challenge",
          "挑戦する": "to challenge",
          "インテリアファブリック": "interior fabric",
          "小物": "accessories",
          "応用": "application",
          "海外市場": "overseas market",
          "展開": "development",
          "伝統技術": "traditional technique",
          "現代的": "modern",
          "活用": "utilization",
          "模索": "search",
          "模索する": "to search for"
        }
      },
      {
        num: 3,
        content: `政策的支援の現状も調査した。文化庁の伝統工芸品産業振興法に基づく支援制度があるが、その効果は限定的だ。

補助金は主に展示会開催や後継者育成事業に充てられるが、個々の職人の生活を直接支えるものではない。

より抜本的な支援として、フランスのメゾン・デ・メティエ・ダール制度が参考になる。これは、伝統工芸の職人を文化財として保護し、経済的支援と社会的地位の向上を図る制度だ。

日本でも、重要無形文化財保持者（人間国宝）制度があるが、認定される人数が限られている。より広範な職人を対象とした支援制度が必要だろう。

しかし、公的支援だけでは限界がある。市場メカニズムと文化保護のバランスをどう取るかが、根本的な問いだ。`,
        vocabulary: {
          "政策的": "policy-related",
          "支援": "support",
          "現状": "current situation",
          "調査": "investigation",
          "調査する": "to investigate",
          "文化庁": "Agency for Cultural Affairs",
          "伝統工芸品": "traditional craft product",
          "産業振興法": "industry promotion law",
          "基づく": "based on",
          "支援制度": "support system",
          "効果": "effect",
          "限定的": "limited",
          "補助金": "subsidy",
          "主に": "mainly",
          "展示会": "exhibition",
          "開催": "holding",
          "後継者": "successor",
          "育成事業": "training project",
          "充てる": "to allocate",
          "個々": "individual",
          "職人": "craftsperson",
          "生活": "livelihood",
          "直接": "directly",
          "支える": "to support",
          "より": "more",
          "抜本的": "fundamental",
          "フランス": "France",
          "メゾン・デ・メティエ・ダール": "Maison des Métiers d'Art",
          "制度": "system",
          "参考": "reference",
          "参考になる": "to be helpful",
          "伝統工芸": "traditional crafts",
          "文化財": "cultural property",
          "保護": "protection",
          "保護する": "to protect",
          "経済的": "economic",
          "社会的地位": "social status",
          "向上": "improvement",
          "図る": "to aim for",
          "日本": "Japan",
          "でも": "also",
          "重要無形文化財保持者": "holder of important intangible cultural property",
          "人間国宝": "living national treasure",
          "認定": "certification",
          "認定される": "to be certified",
          "人数": "number of people",
          "限られる": "to be limited",
          "広範": "wide-ranging",
          "対象": "target",
          "必要": "necessary",
          "だろう": "probably",
          "しかし": "however",
          "公的": "public",
          "だけ": "only",
          "限界": "limit",
          "市場メカニズム": "market mechanism",
          "文化保護": "cultural protection",
          "バランス": "balance",
          "どう": "how",
          "取る": "to achieve",
          "根本的": "fundamental",
          "問い": "question"
        }
      },
      {
        num: 4,
        content: `デジタル技術との融合という新たな可能性も浮上している。3Dスキャナーで伝統技術をデータ化し、VRで体験学習を可能にする試みなどだ。

しかし、これには賛否両論がある。「技術の本質は身体知にあり、デジタル化は本末転倒だ」という批判がある一方、「記録保存と普及のために有用だ」という意見もある。

私は、両者は必ずしも矛盾しないと考える。デジタル技術は伝統技術を代替するものではなく、補完するツールとして活用できる。

重要なのは、技術継承の多層的アプローチだ。徒弟制度による直接伝承、学校教育での基礎訓練、デジタルアーカイブによる記録保存、これらを組み合わせることが効果的だろう。

そして何より、伝統工芸に対する社会の価値認識を高めることが不可欠だ。`,
        vocabulary: {
          "デジタル技術": "digital technology",
          "融合": "fusion",
          "新たな": "new",
          "可能性": "possibility",
          "浮上": "surfacing",
          "浮上する": "to surface",
          "3Dスキャナー": "3D scanner",
          "伝統技術": "traditional technique",
          "データ化": "digitization",
          "データ化する": "to digitize",
          "VR": "virtual reality",
          "体験学習": "experiential learning",
          "可能": "possible",
          "可能にする": "to make possible",
          "試み": "attempt",
          "しかし": "however",
          "賛否両論": "pros and cons",
          "技術": "technique",
          "本質": "essence",
          "身体知": "bodily knowledge",
          "にあり": "lies in",
          "本末転倒": "putting the cart before the horse",
          "批判": "criticism",
          "一方": "on the other hand",
          "記録保存": "archiving",
          "普及": "dissemination",
          "有用": "useful",
          "意見": "opinion",
          "私": "I",
          "両者": "both",
          "必ずしも": "not necessarily",
          "矛盾": "contradiction",
          "矛盾する": "to contradict",
          "考える": "to think",
          "代替": "replacement",
          "代替する": "to replace",
          "補完": "complement",
          "補完する": "to complement",
          "ツール": "tool",
          "活用": "utilization",
          "活用できる": "can be utilized",
          "重要": "important",
          "継承": "succession",
          "多層的": "multi-layered",
          "アプローチ": "approach",
          "徒弟制度": "apprenticeship system",
          "直接": "direct",
          "伝承": "transmission",
          "学校教育": "school education",
          "基礎訓練": "basic training",
          "デジタルアーカイブ": "digital archive",
          "組み合わせる": "to combine",
          "効果的": "effective",
          "だろう": "probably",
          "そして": "and",
          "何より": "above all",
          "伝統工芸": "traditional crafts",
          "対する": "toward",
          "社会": "society",
          "価値認識": "value recognition",
          "高める": "to raise",
          "不可欠": "indispensable"
        }
      },
      {
        num: 5,
        content: `最終的な論文では、「持続可能な伝統工芸継承モデル」を提案した。それは、経済的自立、技術伝承、文化価値の再評価の三本柱からなる。

経済的自立のためには、新市場開拓と付加価値向上が必要だ。技術伝承のためには、多様な教育方法の組み合わせが有効だ。文化価値の再評価のためには、教育と広報の充実が重要だ。

指導教授からは「実証的研究に基づいた、現実的かつ包括的な提案だ」との評価を受けた。

この研究を通じて、伝統と革新は対立概念ではないことを学んだ。伝統を守るためにこそ、革新が必要なのだ。

グローバル化の時代だからこそ、固有の文化的アイデンティティの保持が重要性を増す。伝統工芸の継承は、単なる過去の保存ではなく、未来への創造的継承なのだと確信するに至った。`,
        vocabulary: {
          "最終的": "final",
          "論文": "paper",
          "持続可能": "sustainable",
          "伝統工芸": "traditional crafts",
          "継承": "succession",
          "モデル": "model",
          "提案": "proposal",
          "提案する": "to propose",
          "経済的自立": "economic independence",
          "技術伝承": "technical transmission",
          "文化価値": "cultural value",
          "再評価": "reevaluation",
          "三本柱": "three pillars",
          "からなる": "to consist of",
          "新市場開拓": "new market development",
          "付加価値": "added value",
          "向上": "improvement",
          "必要": "necessary",
          "多様": "diverse",
          "教育方法": "educational method",
          "組み合わせ": "combination",
          "有効": "effective",
          "教育": "education",
          "広報": "public relations",
          "充実": "enhancement",
          "重要": "important",
          "指導教授": "thesis advisor",
          "実証的研究": "empirical research",
          "基づく": "based on",
          "現実的": "realistic",
          "かつ": "and",
          "包括的": "comprehensive",
          "提案": "proposal",
          "評価": "evaluation",
          "受ける": "to receive",
          "研究": "research",
          "通じて": "through",
          "伝統": "tradition",
          "革新": "innovation",
          "対立概念": "opposing concept",
          "学ぶ": "to learn",
          "守る": "to protect",
          "ためにこそ": "precisely in order to",
          "グローバル化": "globalization",
          "時代": "era",
          "だからこそ": "precisely because",
          "固有": "unique",
          "文化的": "cultural",
          "アイデンティティ": "identity",
          "保持": "preservation",
          "重要性": "importance",
          "増す": "to increase",
          "単なる": "mere",
          "過去": "past",
          "保存": "preservation",
          "未来": "future",
          "創造的": "creative",
          "確信": "conviction",
          "確信する": "to be convinced",
          "至る": "to reach"
        }
      }
    ],
    quizzes: [
      {
        id: 'quiz-25-1',
        question: '主人公が研究対象として選んだ伝統工芸は何ですか。',
        type: '読解',
        choices: [
          { text: '西陣織', correct: true, explanation: '「京都の西陣織を事例として選んだ」と書かれています。' },
          { text: '有田焼', correct: false, explanation: '有田焼は選ばれていません。' },
          { text: '漆器', correct: false, explanation: '漆器は選ばれていません。' },
          { text: '友禅染', correct: false, explanation: '友禅染は選ばれていません。' }
        ]
      },
      {
        id: 'quiz-25-2',
        question: '若手職人が語った修行期間中の月収はいくらですか。',
        type: '読解',
        choices: [
          { text: '約15万円', correct: true, explanation: '「その間の収入は月15万円程度」と職人が語りました。' },
          { text: '約20万円', correct: false, explanation: '20万円ではありません。' },
          { text: '約10万円', correct: false, explanation: '10万円ではありません。' },
          { text: '約30万円', correct: false, explanation: '30万円ではありません。' }
        ]
      },
      {
        id: 'quiz-25-3',
        question: '「抜本的」の意味は何ですか。',
        type: '語彙',
        choices: [
          { text: '根本から改める、徹底的な', correct: true, explanation: '「抜本的」は物事の根本から改めることを意味します。' },
          { text: '部分的な', correct: false, explanation: 'それは逆の意味です。' },
          { text: '一時的な', correct: false, explanation: 'それは逆の意味です。' },
          { text: '表面的な', correct: false, explanation: 'それは逆の意味です。' }
        ]
      },
      {
        id: 'quiz-25-4',
        question: '主人公が提案した「持続可能な伝統工芸継承モデル」の三本柱に含まれないものはどれですか。',
        type: '読解',
        choices: [
          { text: '政府の直接補助', correct: true, explanation: '三本柱は「経済的自立、技術伝承、文化価値の再評価」です。政府の直接補助は含まれていません。' },
          { text: '経済的自立', correct: false, explanation: 'これは三本柱の一つです。' },
          { text: '技術伝承', correct: false, explanation: 'これは三本柱の一つです。' },
          { text: '文化価値の再評価', correct: false, explanation: 'これは三本柱の一つです。' }
        ]
      },
      {
        id: 'quiz-25-5',
        question: '「確信するに至る」の意味は何ですか。',
        type: '語彙',
        choices: [
          { text: '強く信じるようになる', correct: true, explanation: '「確信するに至る」は何かを強く信じるようになることです。' },
          { text: '疑うようになる', correct: false, explanation: 'それは逆の意味です。' },
          { text: '諦める', correct: false, explanation: 'それは「諦める」です。' },
          { text: '忘れる', correct: false, explanation: 'それは「忘れる」です。' }
        ]
      }
    ]
  }
};

export default storyContentsN1Final;
