// Story 15 quizzes
{
  quiz_id: 'quiz-15-1',
  story_id: '15',
  question_text: '土曜日の朝、主人公が考えたことは何ですか？',
  question_type: '読解',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '「今日は何をしようかな」と考えます。',
  choices: [
    { choice_text: '今日は何をしようかな', is_correct: true, explanation: '正解です！土曜日の朝、主人公は「今日は何をしようかな」と考えました。週末の計画を立てる時の自然な表現です。' },
    { choice_text: '明日は何時に起きようかな', is_correct: false, explanation: '不正解です。これは日曜日の計画を考える時の話です。' },
    { choice_text: '友達に電話しようかな', is_correct: false, explanation: '不正解です。電話は選択肢の一つですが、最初に考えたことではありません。' },
    { choice_text: '仕事に行かなければならない', is_correct: false, explanation: '不正解です。土曜日と日曜日は休みです。' },
  ],
},
{
  quiz_id: 'quiz-15-2',
  story_id: '15',
  question_text: '「〜つもりです」はどんな意味ですか？',
  question_type: '語彙',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '〜つもりです = I intend to... / I plan to...',
  choices: [
    { choice_text: 'I intend to... / I plan to...', is_correct: true, explanation: '正解です！「〜つもりです」は意図や計画を表す表現で、英語の "I intend to..." や "I plan to..." に相当します。未来の予定を話す時に使います。' },
    { choice_text: 'I want to...', is_correct: false, explanation: '不正解です。これは「〜たい」の意味です。' },
    { choice_text: 'I must...', is_correct: false, explanation: '不正解です。これは「〜なければならない」の意味です。' },
    { choice_text: 'I finished...', is_correct: false, explanation: '不正解です。これは「〜ました」の意味です。' },
  ],
},
{
  quiz_id: 'quiz-15-3',
  story_id: '15',
  question_text: '「勉強してから、買い物に行きます」の「〜てから」はどんな意味ですか？',
  question_type: '文法',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '〜てから = after doing...',
  choices: [
    { choice_text: 'After doing...', is_correct: true, explanation: '正解です！「〜てから」は「〜した後で」という意味で、英語の "after doing..." に相当します。ある行動の後に別の行動をする順序を表す時に使います。' },
    { choice_text: 'Before doing...', is_correct: false, explanation: '不正解です。これは「〜前に」の意味です。' },
    { choice_text: 'While doing...', is_correct: false, explanation: '不正解です。これは「〜ながら」の意味です。' },
    { choice_text: 'Without doing...', is_correct: false, explanation: '不正解です。これは「〜ないで」の意味です。' },
  ],
},
