// Story 17 quizzes
{
  quiz_id: 'quiz-17-1',
  story_id: '17',
  question_text: '日本の電車で「快速」とは何ですか？',
  question_type: '読解',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '快速電車は主要駅にだけ停まる',
  choices: [
    { choice_text: '主要駅にだけ停まる、速い電車', is_correct: true, explanation: '正解です！「快速」は主要な駅にだけ停車して、速く目的地に到着できる電車です。各駅停車よりも速いですが、特急よりは遅いです。通勤や移動時間を短縮したい時に便利です。' },
    { choice_text: 'すべての駅に停まる電車', is_correct: false, explanation: '不正解です。すべての駅に停まるのは「各駅停車」です。' },
    { choice_text: '特別料金が必要な電車', is_correct: false, explanation: '不正解です。特別料金が必要なのは「特急」や「新幹線」です。快速は通常の運賃で乗れます。' },
    { choice_text: '夜だけ走る電車', is_correct: false, explanation: '不正解です。快速は昼間も夜も走っています。' },
  ],
},
{
  quiz_id: 'quiz-17-2',
  story_id: '17',
  question_text: '「〜てから」はどんな意味ですか？',
  question_type: '語彙',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '〜てから = after doing',
  choices: [
    { choice_text: 'after doing', is_correct: true, explanation: '正解です！「〜てから」は「〜した後で」という意味で、英語の "after doing" に相当します。例：「切符を買ってから、改札を通ります」(After buying a ticket, I go through the ticket gate)。N3レベルの重要文法です。' },
    { choice_text: 'before doing', is_correct: false, explanation: '不正解です。これは「〜前に」の意味です。' },
    { choice_text: 'while doing', is_correct: false, explanation: '不正解です。これは「〜ながら」の意味です。' },
    { choice_text: 'without doing', is_correct: false, explanation: '不正解です。これは「〜ないで」の意味です。' },
  ],
},
{
  quiz_id: 'quiz-17-3',
  story_id: '17',
  question_text: '日本の電車システムの特徴は何ですか？',
  question_type: '文化',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '日本の電車は時刻が正確で、ほとんど遅れない',
  choices: [
    { choice_text: '時刻が正確で、ほとんど遅れない', is_correct: true, explanation: '正解です！日本の電車は世界的に有名な正確さで知られています。平均遅延時間は1分以下で、時刻表通りに運行されます。この正確さは日本人の時間に対する意識の高さと、優れた運行管理システムによるものです。' },
    { choice_text: 'よく遅れるので、余裕を持って出発する必要がある', is_correct: false, explanation: '不正解です。日本の電車は世界で最も時間に正確な交通機関の一つです。' },
    { choice_text: '料金が安く、誰でも乗れる', is_correct: false, explanation: '不正解です。日本の電車料金は比較的高いですが、サービスの質が高いです。' },
    { choice_text: '夜遅くまで運行していない', is_correct: false, explanation: '不正解です。東京などの大都市では深夜まで運行しています。ただし、終電（最終電車）の時間は決まっています。' },
  ],
},
