// Story 13 quizzes
{
  quiz_id: 'quiz-13-1',
  story_id: '13',
  question_text: '店員さんは最初に何と聞きましたか？',
  question_type: '読解',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '「いらっしゃいませ！何名様ですか？」と店員さんが聞きます。',
  choices: [
    { choice_text: '何名様ですか？', is_correct: true, explanation: '正解です！レストランに入ると、店員さんはまず「何名様ですか？」（How many people?）と人数を確認します。これは日本のレストランでの標準的な接客です。' },
    { choice_text: 'ご予約はありますか？', is_correct: false, explanation: '不正解です。予約の確認は人数確認の後に聞かれることが多いです。' },
    { choice_text: 'お飲み物は何にしますか？', is_correct: false, explanation: '不正解です。飲み物は席に着いてから聞かれます。' },
    { choice_text: 'メニューは決まりましたか？', is_correct: false, explanation: '不正解です。これは注文を取る時の質問です。' },
  ],
},
{
  quiz_id: 'quiz-13-2',
  story_id: '13',
  question_text: '「〜をください」の意味は何ですか？',
  question_type: '語彙',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '〜をください = Please give me 〜',
  choices: [
    { choice_text: 'Please give me 〜', is_correct: true, explanation: '正解です！「〜をください」は「Please give me 〜」という意味で、何かを注文したり頼んだりする時に使う基本的な表現です。レストランでの注文に最適です。' },
    { choice_text: 'I don\'t want 〜', is_correct: false, explanation: '不正解です。これは「〜はいりません」の意味です。' },
    { choice_text: 'Do you have 〜?', is_correct: false, explanation: '不正解です。これは「〜はありますか？」の意味です。' },
    { choice_text: 'I\'m looking for 〜', is_correct: false, explanation: '不正解です。これは「〜を探しています」の意味です。' },
  ],
},
{
  quiz_id: 'quiz-13-3',
  story_id: '13',
  question_text: '日本で食事を始める前に何と言いますか？',
  question_type: '文化',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: 'いただきます',
  choices: [
    { choice_text: 'いただきます', is_correct: true, explanation: '正解です！「いただきます」は食事を始める前に言う言葉です。食べ物への感謝を表します。食事が終わった後は「ごちそうさまでした」と言います。' },
    { choice_text: 'おはようございます', is_correct: false, explanation: '不正解です。これは朝の挨拶です。' },
    { choice_text: 'ごちそうさまでした', is_correct: false, explanation: '不正解です。これは食事が終わった後に言う言葉です。' },
    { choice_text: 'よろしくお願いします', is_correct: false, explanation: '不正解です。これは自己紹介や依頼の時に使います。' },
  ],
},
