// Story 10 quizzes
{
  quiz_id: 'quiz-10-1',
  story_id: '10',
  question_text: 'アレックスは日本語学校で何を勉強しましたか？',
  question_type: '読解',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '今日は挨拶と自己紹介を勉強しました',
  choices: [
    { choice_text: '挨拶と自己紹介', is_correct: true, explanation: '正解です！本文で「今日は挨拶と自己紹介を勉強しました」と書いてあります。' },
    { choice_text: '数字と時間', is_correct: false, explanation: '不正解です。数字と時間は明日勉強する予定です。' },
    { choice_text: '漢字と文法', is_correct: false, explanation: '不正解です。漢字と文法については触れていません。' },
    { choice_text: '料理と文化', is_correct: false, explanation: '不正解です。料理と文化については触れていません。' },
  ],
},
{
  quiz_id: 'quiz-10-2',
  story_id: '10',
  question_text: '「はじめまして」はいつ使いますか？',
  question_type: '語彙',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: 'はじめまして。私はアレックスです。',
  choices: [
    { choice_text: '朝の挨拶', is_correct: false, explanation: '不正解です。朝の挨拶は「おはようございます」です。' },
    { choice_text: '初めて会う人への挨拶', is_correct: true, explanation: '正解です！「はじめまして」は初めて会う人に使う挨拶です。英語の"Nice to meet you"と同じ意味です。' },
    { choice_text: '別れの挨拶', is_correct: false, explanation: '不正解です。別れの挨拶は「さようなら」です。' },
    { choice_text: 'お礼を言う時', is_correct: false, explanation: '不正解です。お礼を言う時は「ありがとうございます」です。' },
  ],
},
{
  quiz_id: 'quiz-10-3',
  story_id: '10',
  question_text: '自己紹介の最後に何と言いますか？',
  question_type: '文化',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: 'よろしくお願いします',
  choices: [
    { choice_text: 'ありがとうございます', is_correct: false, explanation: '不正解です。「ありがとうございます」はお礼を言う時に使います。' },
    { choice_text: 'すみません', is_correct: false, explanation: '不正解です。「すみません」は謝る時や呼びかける時に使います。' },
    { choice_text: 'よろしくお願いします', is_correct: true, explanation: '正解です！自己紹介の最後には「よろしくお願いします」と言います。これは「これからお世話になります」という意味です。' },
    { choice_text: 'さようなら', is_correct: false, explanation: '不正解です。「さようなら」は別れの挨拶です。' },
  ],
},
