// Story 12 quizzes
{
  quiz_id: 'quiz-12-1',
  story_id: '12',
  question_text: 'カフェテリアのメニューに何がありましたか？',
  question_type: '読解',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '今日のメニューは：カレー、ラーメン、寿司、サラダがあります。',
  choices: [
    { choice_text: 'カレー、ラーメン、寿司、サラダ', is_correct: true, explanation: '正解です！本文で「今日のメニューは：カレー、ラーメン、寿司、サラダがあります」と書いてあります。' },
    { choice_text: 'ハンバーガー、ピザ、パスタ', is_correct: false, explanation: '不正解です。これらは今日のメニューにありません。' },
    { choice_text: '焼肉、天ぷら、うどん', is_correct: false, explanation: '不正解です。これらは後で話題に出ますが、カフェテリアのメニューではありません。' },
    { choice_text: 'ケーキ、アイスクリーム、クッキー', is_correct: false, explanation: '不正解です。これらはデザートです。' },
  ],
},
{
  quiz_id: 'quiz-12-2',
  story_id: '12',
  question_text: '「好きです」の反対の意味は何ですか？',
  question_type: '語彙',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '好きです / 嫌いです',
  choices: [
    { choice_text: '嫌いです', is_correct: true, explanation: '正解です！「好きです」の反対は「嫌いです」です。英語の"like"と"dislike"の関係です。' },
    { choice_text: 'おいしいです', is_correct: false, explanation: '不正解です。「おいしいです」は食べ物の味を表す言葉で、好みとは違います。' },
    { choice_text: '甘いです', is_correct: false, explanation: '不正解です。「甘いです」は味の種類を表す言葉です。' },
    { choice_text: '辛いです', is_correct: false, explanation: '不正解です。「辛いです」は味の種類を表す言葉です。' },
  ],
},
{
  quiz_id: 'quiz-12-3',
  story_id: '12',
  question_text: '「〜が大好きです」はどんな意味ですか？',
  question_type: '文法',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '大好きです = really love / love very much',
  choices: [
    { choice_text: 'I really love 〜', is_correct: true, explanation: '正解です！「大好き」は「とても好き」という意味で、英語の"really love"や"love very much"に相当します。「好き」よりも強い表現です。' },
    { choice_text: 'I hate 〜', is_correct: false, explanation: '不正解です。これは「大嫌い」の意味です。' },
    { choice_text: 'I don\'t like 〜 very much', is_correct: false, explanation: '不正解です。これは「あまり好きじゃない」の意味です。' },
    { choice_text: 'I\'m okay with 〜', is_correct: false, explanation: '不正解です。これは「まあまあ」「普通」という意味です。' },
  ],
},
