// Story 11 quizzes
{
  quiz_id: 'quiz-11-1',
  story_id: '11',
  question_text: '主人公の家族は何人ですか？',
  question_type: '読解',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '父、母、兄、妹、そして私です。5人家族です。',
  choices: [
    { choice_text: '3人', is_correct: false, explanation: '不正解です。家族はもっと多いです。' },
    { choice_text: '4人', is_correct: false, explanation: '不正解です。田中さん一家は4人ですが、主人公の家族は違います。' },
    { choice_text: '5人', is_correct: true, explanation: '正解です！本文で「父、母、兄、妹、そして私です。5人家族です。」と書いてあります。' },
    { choice_text: '6人', is_correct: false, explanation: '不正解です。家族は6人よりも少ないです。' },
  ],
},
{
  quiz_id: 'quiz-11-2',
  story_id: '11',
  question_text: '「父」と「母」を合わせて何と言いますか？',
  question_type: '語彙',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '家族',
  choices: [
    { choice_text: '先生', is_correct: false, explanation: '不正解です。「先生」は teacher の意味です。' },
    { choice_text: '友達', is_correct: false, explanation: '不正解です。「友達」は friend の意味です。' },
    { choice_text: '家族', is_correct: true, explanation: '正解です！「父」と「母」などを合わせて「家族」と言います。英語の"family"の意味です。' },
    { choice_text: '学生', is_correct: false, explanation: '不正解です。「学生」は student の意味です。' },
  ],
},
{
  quiz_id: 'quiz-11-3',
  story_id: '11',
  question_text: '主人公の母の仕事は何ですか？',
  question_type: '読解',
  difficulty_level: 'N5',
  is_ai_generated: false,
  source_text: '母は看護師です',
  choices: [
    { choice_text: '先生', is_correct: false, explanation: '不正解です。先生ではありません。' },
    { choice_text: '看護師', is_correct: true, explanation: '正解です！本文で「母は看護師です」と書いてあります。' },
    { choice_text: '会社員', is_correct: false, explanation: '不正解です。会社員は父の仕事です。' },
    { choice_text: '学生', is_correct: false, explanation: '不正解です。母は学生ではありません。' },
  ],
},
