// Story 18 quizzes
{
  quiz_id: 'quiz-18-1',
  story_id: '18',
  question_text: '郵便局で「書留」とは何ですか？',
  question_type: '読解',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '書留は配達を記録して、安全に送るサービス',
  choices: [
    { choice_text: '配達を記録して、安全に送るサービス', is_correct: true, explanation: '正解です！「書留」は、郵便物の引き受けから配達までを記録し、万が一紛失した場合は実損額を賠償するサービスです。大切な書類や貴重品を送る時に使います。追跡番号で配達状況を確認できるので安心です。' },
    { choice_text: '速く届くサービス', is_correct: false, explanation: '不正解です。速く届くのは「速達」です。書留は安全性を重視したサービスです。' },
    { choice_text: '安く送れるサービス', is_correct: false, explanation: '不正解です。書留は通常の郵便よりも料金が高くなります。' },
    { choice_text: '大きな荷物を送るサービス', is_correct: false, explanation: '不正解です。大きな荷物は「ゆうパック」などの宅配サービスを使います。' },
  ],
},
{
  quiz_id: 'quiz-18-2',
  story_id: '18',
  question_text: '「〜てもらう」の意味は何ですか？',
  question_type: '語彙',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '〜てもらう = receive a favor / have someone do',
  choices: [
    { choice_text: 'receive a favor / have someone do', is_correct: true, explanation: '正解です！「〜てもらう」は他の人にしてもらって恩恵を受けるという意味です。例：「窓口の人に説明してもらいました」(I had the counter staff explain it to me)。相手の行動から利益を受ける時に使う、N3レベルの授受表現です。' },
    { choice_text: 'do a favor for someone', is_correct: false, explanation: '不正解です。これは「〜てあげる」の意味です。' },
    { choice_text: 'want to do', is_correct: false, explanation: '不正解です。これは「〜たい」の意味です。' },
    { choice_text: 'must do', is_correct: false, explanation: '不正解です。これは「〜なければならない」の意味です。' },
  ],
},
{
  quiz_id: 'quiz-18-3',
  story_id: '18',
  question_text: '日本の郵便サービスの特徴は何ですか？',
  question_type: '文化',
  difficulty_level: 'N3',
  is_ai_generated: false,
  source_text: '日本の郵便は信頼性が高く、時間通りに届く',
  choices: [
    { choice_text: '信頼性が高く、時間通りに届く', is_correct: true, explanation: '正解です！日本郵便は世界的に信頼性の高いサービスで知られています。国内郵便はほとんどの場合、翌日または翌々日に届きます。また、配達員の丁寧な対応や、追跡システムの充実も特徴です。紛失や破損も非常に少ないです。' },
    { choice_text: '料金が安いが、遅い', is_correct: false, explanation: '不正解です。日本の郵便料金は適正価格で、配達は速いです。' },
    { choice_text: '荷物がよく無くなる', is_correct: false, explanation: '不正解です。日本の郵便サービスは紛失率が非常に低いです。' },
    { choice_text: '窓口でしか送れない', is_correct: false, explanation: '不正解です。ポストからも送れますし、集荷サービスもあります。' },
  ],
},
