// Story 14 quizzes
{
  quiz_id: 'quiz-14-1',
  story_id: '14',
  question_text: 'ユウタさんは最初に何と聞きましたか？',
  question_type: '読解',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '「週末、暇？一緒に遊びませんか？」',
  choices: [
    { choice_text: '週末、暇？一緒に遊びませんか？', is_correct: true, explanation: '正解です！ユウタさんは「週末、暇？一緒に遊びませんか？」と誘っています。これは友達を誘う時の自然な表現です。' },
    { choice_text: '明日は何時に会いますか？', is_correct: false, explanation: '不正解です。時間の確認はこの後に行います。' },
    { choice_text: 'どこで会いましょうか？', is_correct: false, explanation: '不正解です。場所の決定は活動を決めた後です。' },
    { choice_text: '何を食べたいですか？', is_correct: false, explanation: '不正解です。これは食事の話であり、最初の誘いではありません。' },
  ],
},
{
  quiz_id: 'quiz-14-2',
  story_id: '14',
  question_text: '「〜ませんか」の意味は何ですか？',
  question_type: '語彙',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '〜ませんか = Won\'t you...? / Shall we...?',
  choices: [
    { choice_text: 'Won\'t you...? / Shall we...?', is_correct: true, explanation: '正解です！「〜ませんか」は誘いや提案を表す表現で、英語の "Won\'t you...?" や "Shall we...?" に相当します。丁寧に人を誘う時に使います。' },
    { choice_text: 'I want to...', is_correct: false, explanation: '不正解です。これは「〜たい」の意味です。' },
    { choice_text: 'I don\'t want to...', is_correct: false, explanation: '不正解です。これは「〜たくない」の意味です。' },
    { choice_text: 'You must...', is_correct: false, explanation: '不正解です。これは「〜なければならない」の意味です。' },
  ],
},
{
  quiz_id: 'quiz-14-3',
  story_id: '14',
  question_text: '「映画を見ましょう」はどんな意味ですか？',
  question_type: '文法',
  difficulty_level: 'N4',
  is_ai_generated: false,
  source_text: '〜ましょう = Let\'s...',
  choices: [
    { choice_text: 'Let\'s watch a movie', is_correct: true, explanation: '正解です！「〜ましょう」は提案や勧誘を表す表現で、英語の "Let\'s..." に相当します。一緒に何かをすることを提案する時に使います。' },
    { choice_text: 'I\'m watching a movie', is_correct: false, explanation: '不正解です。これは「映画を見ています」の意味です。' },
    { choice_text: 'I want to watch a movie', is_correct: false, explanation: '不正解です。これは「映画を見たい」の意味です。' },
    { choice_text: 'Did you watch a movie?', is_correct: false, explanation: '不正解です。これは「映画を見ましたか？」の意味です。' },
  ],
},
