import * as fs from 'fs';

// Read seed_complete.ts
const content = fs.readFileSync('prisma/seed_complete.ts', 'utf-8');

// Story definitions to add required fields
const storyUpdates = [
  {
    old: `story_id: '1',
      title: '東京での新しい生活',
      description: '初めて東京に来た留学生の1日を追体験。渋谷での選択があなたの物語を変えます。',
      level_jlpt: 'N3',
      level_cefr: 'B1',
      estimated_time: 10,
      root_chapter_id: 'ch-1-1',`,
    new: `story_id: '1',
      title: '東京での新しい生活',
      title_en: 'A New Life in Tokyo',
      description: '初めて東京に来た留学生の1日を追体験。渋谷での選択があなたの物語を変えます。',
      description_en: 'Experience the first day of an international student in Tokyo. Your choices in Shibuya will change your story.',
      category: 'daily_life',
      difficulty_level: 'intermediate',
      level_jlpt: 'N3',
      level_cefr: 'B1',
      estimated_time: 10,
      estimated_duration_minutes: 10,
      is_active: true,
      root_chapter_id: 'ch-1-1',`,
  },
  {
    old: `story_id: '2',
      title: 'カフェでの出会い',
      description: '偶然入ったカフェで始まる、心温まる友情のストーリー。',
      level_jlpt: 'N4',
      level_cefr: 'A2',
      estimated_time: 8,
      root_chapter_id: 'ch-2-1',`,
    new: `story_id: '2',
      title: 'カフェでの出会い',
      title_en: 'Meeting at a Cafe',
      description: '偶然入ったカフェで始まる、心温まる友情のストーリー。',
      description_en: 'A heartwarming story of friendship that begins at a cafe you entered by chance.',
      category: 'social',
      difficulty_level: 'beginner',
      level_jlpt: 'N4',
      level_cefr: 'A2',
      estimated_time: 8,
      estimated_duration_minutes: 8,
      is_active: true,
      root_chapter_id: 'ch-2-1',`,
  },
  {
    old: `story_id: '3',
      title: '初めてのコンビニ',
      description: '初めて日本のコンビニで買い物をする体験。便利な日本のコンビニ文化を学びます。',
      level_jlpt: 'N5',
      level_cefr: 'A1',
      estimated_time: 6,
      root_chapter_id: 'ch-3-1',`,
    new: `story_id: '3',
      title: '初めてのコンビニ',
      title_en: 'First Time at a Convenience Store',
      description: '初めて日本のコンビニで買い物をする体験。便利な日本のコンビニ文化を学びます。',
      description_en: 'Experience shopping at a Japanese convenience store for the first time. Learn about the convenient convenience store culture of Japan.',
      category: 'daily_life',
      difficulty_level: 'beginner',
      level_jlpt: 'N5',
      level_cefr: 'A1',
      estimated_time: 6,
      estimated_duration_minutes: 6,
      is_active: true,
      root_chapter_id: 'ch-3-1',`,
  },
  {
    old: `story_id: '4',
      title: '駅での待ち合わせ',
      description: '新宿駅で友達と待ち合わせ。日本の大きな駅での体験を学びます。',
      level_jlpt: 'N4',
      level_cefr: 'A2',
      estimated_time: 8,
      root_chapter_id: 'ch-4-1',`,
    new: `story_id: '4',
      title: '駅での待ち合わせ',
      title_en: 'Meeting at the Station',
      description: '新宿駅で友達と待ち合わせ。日本の大きな駅での体験を学びます。',
      description_en: 'Meeting a friend at Shinjuku Station. Learn about experiences at large Japanese train stations.',
      category: 'daily_life',
      difficulty_level: 'beginner',
      level_jlpt: 'N4',
      level_cefr: 'A2',
      estimated_time: 8,
      estimated_duration_minutes: 8,
      is_active: true,
      root_chapter_id: 'ch-4-1',`,
  },
  {
    old: `story_id: '5',
      title: '居酒屋での夜',
      description: '会社の同僚と居酒屋へ。日本の飲み会文化を体験します。',
      level_jlpt: 'N3',
      level_cefr: 'B1',
      estimated_time: 10,
      root_chapter_id: 'ch-5-1',`,
    new: `story_id: '5',
      title: '居酒屋での夜',
      title_en: 'Night at an Izakaya',
      description: '会社の同僚と居酒屋へ。日本の飲み会文化を体験します。',
      description_en: 'Going to an izakaya with work colleagues. Experience Japanese drinking party culture.',
      category: 'social',
      difficulty_level: 'intermediate',
      level_jlpt: 'N3',
      level_cefr: 'B1',
      estimated_time: 10,
      estimated_duration_minutes: 10,
      is_active: true,
      root_chapter_id: 'ch-5-1',`,
  },
  {
    old: `story_id: '6',
      title: '温泉旅行',
      description: '週末の温泉旅行。日本の伝統的な旅館文化と温泉マナーを学びます。',
      level_jlpt: 'N2',
      level_cefr: 'B2',
      estimated_time: 12,
      root_chapter_id: 'ch-6-1',`,
    new: `story_id: '6',
      title: '温泉旅行',
      title_en: 'Hot Spring Trip',
      description: '週末の温泉旅行。日本の伝統的な旅館文化と温泉マナーを学びます。',
      description_en: 'A weekend trip to a hot spring. Learn about traditional Japanese ryokan culture and hot spring etiquette.',
      category: 'culture',
      difficulty_level: 'intermediate',
      level_jlpt: 'N2',
      level_cefr: 'B2',
      estimated_time: 12,
      estimated_duration_minutes: 12,
      is_active: true,
      root_chapter_id: 'ch-6-1',`,
  },
  {
    old: `story_id: '7',
      title: '日本企業での面接',
      description: '日本の会社での就職面接。ビジネスマナーと面接の準備を体験します。',
      level_jlpt: 'N2',
      level_cefr: 'B2',
      estimated_time: 12,
      root_chapter_id: 'ch-7-1',`,
    new: `story_id: '7',
      title: '日本企業での面接',
      title_en: 'Job Interview at a Japanese Company',
      description: '日本の会社での就職面接。ビジネスマナーと面接の準備を体験します。',
      description_en: 'Job interview at a Japanese company. Experience business etiquette and interview preparation.',
      category: 'business',
      difficulty_level: 'advanced',
      level_jlpt: 'N2',
      level_cefr: 'B2',
      estimated_time: 12,
      estimated_duration_minutes: 12,
      is_active: true,
      root_chapter_id: 'ch-7-1',`,
  },
  {
    old: `story_id: '8',
      title: '京都の古寺巡り',
      description: '古都京都で日本の精神性と美学を探求する旅。禅の思想と伝統文化を深く学びます。',
      level_jlpt: 'N1',
      level_cefr: 'C1',
      estimated_time: 15,
      root_chapter_id: 'ch-8-1',`,
    new: `story_id: '8',
      title: '京都の古寺巡り',
      title_en: 'Visiting Ancient Temples in Kyoto',
      description: '古都京都で日本の精神性と美学を探求する旅。禅の思想と伝統文化を深く学びます。',
      description_en: 'A journey to explore Japanese spirituality and aesthetics in the ancient capital of Kyoto. Deeply learn about Zen philosophy and traditional culture.',
      category: 'culture',
      difficulty_level: 'advanced',
      level_jlpt: 'N1',
      level_cefr: 'C1',
      estimated_time: 15,
      estimated_duration_minutes: 15,
      is_active: true,
      root_chapter_id: 'ch-8-1',`,
  },
  {
    old: `story_id: '9',
      title: 'ビジネス交渉',
      description: '日本企業との重要な商談。高度なビジネス日本語と交渉術を学びます。',
      level_jlpt: 'N1',
      level_cefr: 'C1',
      estimated_time: 15,
      root_chapter_id: 'ch-9-1',`,
    new: `story_id: '9',
      title: 'ビジネス交渉',
      title_en: 'Business Negotiation',
      description: '日本企業との重要な商談。高度なビジネス日本語と交渉術を学びます。',
      description_en: 'An important business meeting with a Japanese company. Learn advanced business Japanese and negotiation skills.',
      category: 'business',
      difficulty_level: 'advanced',
      level_jlpt: 'N1',
      level_cefr: 'C1',
      estimated_time: 15,
      estimated_duration_minutes: 15,
      is_active: true,
      root_chapter_id: 'ch-9-1',`,
  },
];

let updatedContent = content;

// Apply all story updates
for (const update of storyUpdates) {
  updatedContent = updatedContent.replace(update.old, update.new);
}

// Write updated file
fs.writeFileSync('prisma/seed_complete.ts', updatedContent, 'utf-8');

console.log('Updated seed_complete.ts with required fields and translations');
